"""empty message

Revision ID: 6cb5cae4a6b4
Revises: 1a847615dae5
Create Date: 2019-11-29 00:50:38.944454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb5cae4a6b4'
down_revision = '1a847615dae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('create_uid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_foreign_key', 'users', ['create_uid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('create_uid')
        batch_op.drop_column('close_date')

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
